version: 1.0.{build}
image: Visual Studio 2022
before_build:
  - ps: .\scripts\build.ps1
build_script:
  - ps: dotnet build -c Release
test_script:
  - ps: dotnet test src/ATMSystem.Tests/ATMSystem.Tests.csproj --collect:"XPlat Code Coverage"
on_success:
  - ps: .\scripts\build.ps1